name: Terraform Lambda Plan and Apply

on:
  push:
    branches:
      - main

env:
  AWS_REGION: us-east-2
  BUCKET_NAME: terraform-state-bharath-lambda

jobs:
  plan:
    name: Terraform Plan (Dev)
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: .

    steps:
      - name: ✅ Checkout code
        uses: actions/checkout@v3

      - name: 🔐 Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: 📦 Create S3 Backend Bucket (if not exists)
        run: |
          if ! aws s3api head-bucket --bucket "$BUCKET_NAME" 2>/dev/null; then
            echo "Creating backend S3 bucket..."
            aws s3api create-bucket --bucket "$BUCKET_NAME" --region "$AWS_REGION" --create-bucket-configuration LocationConstraint="$AWS_REGION"

            aws s3api put-bucket-versioning \
              --bucket "$BUCKET_NAME" \
              --versioning-configuration Status=Enabled

            aws s3api put-bucket-encryption \
              --bucket "$BUCKET_NAME" \
              --server-side-encryption-configuration '{
                "Rules": [{
                  "ApplyServerSideEncryptionByDefault": {
                    "SSEAlgorithm": "AES256"
                  }
                }]
              }'
          else
            echo "✅ S3 backend bucket already exists."
          fi

      - name: 🧰 Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.6.0

      - name: 📦 Create Lambda ZIP Archive
        run: |
          zip lambda_function_payload.zip lambda.js

      - name: ⚙️ Terraform Init
        run: |
          terraform init \
            -backend-config="bucket=$BUCKET_NAME" \
            -backend-config="key=lambda/dev/terraform.tfstate" \
            -backend-config="region=$AWS_REGION"

      - name: 🔍 Terraform Plan
        run: terraform plan -var-file="environments/dev.tfvars" -out=tfplan

      - name: 📤 Upload Plan Artifact
        uses: actions/upload-artifact@v4
        with:
          name: tfplan
          path: tfplan

      - name: 💰 Show Lambda Cost Estimate
        run: |
          {
            echo "## 💰 Estimated Monthly Costs (Lambda)"
            echo ""
            echo "| Resource         | Quantity | Pricing (approx) | Total |"
            echo "|------------------|----------|------------------|--------|"
            echo "| Lambda Execution | 1M req   | ~$0.20/million   | ~$0.20 |"
            echo "| IAM Role         | 1        | ~$0              | ~$0    |"
            echo ""
            echo "**Total Estimate:** ~$0.20/month"
          } >> $GITHUB_STEP_SUMMARY

  apply:
    name: Terraform Apply (Manual Approval)
    runs-on: ubuntu-latest
    needs: plan
    environment:
      name: dev-approval
      url: https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}

    defaults:
      run:
        working-directory: .

    steps:
      - name: ✅ Checkout code
        uses: actions/checkout@v3

      - name: 🔐 Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: 🧰 Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.6.0

      - name: 📦 Create Lambda ZIP Archive (again for apply)
        run: |
          zip lambda_function_payload.zip lambda.js

      - name: ⚙️ Terraform Init
        run: |
          terraform init \
            -backend-config="bucket=$BUCKET_NAME" \
            -backend-config="key=lambda/dev/terraform.tfstate" \
            -backend-config="region=$AWS_REGION"

      - name: 📥 Download Plan Artifact
        uses: actions/download-artifact@v4
        with:
          name: tfplan
          path: .

      - name: 🚀 Terraform Apply
        run: terraform apply tfplan

